version: "3.7"

services:
  myredis:
    image: redis

  myvotingapp:
    image: rmuhamed/votingapp:0.1
    build:
      dockerfile: Dockerfile
      context: ./src/votingapp
    ports:
      - 8080:80
    environment:
      REDIS: "myredis:6379"

  mytest:
    image: rmuhamed/votingapp-test
    build:
      context: ./test
    environment:
      VOTINGAPP_HOST: "myvotingapp"
