version: "3.7"

services: 
  myredis:
    image: redis

  myvotingapp:
    image: rmuhamed/votingapp
    build:
      dockerfile: Dockerfile
      context: ./src/votingapp
    environment:
      REDIS: "myredis:6379"

  mytest:
    image: rmuhamed/votingapp-test
    build:
      dockerfile: Dockerfile
      context: ./test
    environment: 
      VOTINGAPP_HOST: "myreverseproxy"

  myreverseproxy:
    image: rmuhamed/reverse-proxy
    build:
      dockerfile: Dockerfile
      context: ./nginx
    ports: 
      - 8080:80

