apiVersion: v1
kind: Namespace
metadata:
  name: votingapp
spec:
  finalizers:
  - kubernetes
---
apiVersion: v1
kind: Pod
metadata:
  labels:
    app: myvotingapp
  name: myvotingapp
  namespace: votingapp
spec:
  containers:
  - image: rmuhamed/votingapp:0.1
    name: myvotingapp
    env:
      - name: REDIS
        value: "myredis:6379"
---
apiVersion: v1
kind: Pod
metadata:
  labels:
    app: myredis
  name: myredis
  namespace: votingapp
spec:
  containers:
  - image: redis
    name: myredis
---
apiVersion: v1
kind: Service
metadata:
  name: myvotingapp
  namespace: votingapp
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: myvotingapp
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: myredis
  namespace: votingapp
spec:
  ports:
  - port: 6379
    targetPort: 6379
  selector:
    app: myredis
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: votingapp
spec:
  selector:
    matchLabels:
      app: votingapp
  template:
    metadata:
      labels:
        app: myvotingapp
    spec:
      containers:
      - name: votingapp
        image: rmuhamed/votingapp
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        env:
          - name: VOTINGAPP_HOST
            value: myvotingapp
        
