apiVersion: v1
kind: Namespace
metadata:
  name: votingapp
spec:
  finalizers:
  - kubernetes
---
apiVersion: v1
kind: Pod
metadata:
  labels:
    app: myvotingapp
  name: myvotingapp
  namespace: votingapp
spec:
  containers:
  - image: rmuhamed/votingapp:0.1
    name: myvotingapp
    env:
      - name: redis
        value: "myredis"
---
apiVersion: v1
kind: Pod
metadata:
  labels:
    app: myredis
  name: myredis
  namespace: votingapp
spec:
  containers:
  - image: rredis
    name: myredis
---
apiVersion: v1
kind: Service
metadata:
  name: myvotingapp
  namespace: votingapp
spec:
  ports:
  - nodePort: 31940
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: myvotingapp
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  name: myredis
  namespace: votingapp
spec:
  ports:
  - port: 6379
    targetPort: 6379
  selector:
    app: myredis
  #type: NodePort
